-- ============================================================================
-- bank-reconciliation-migration.sql
--
-- Bank Reconciliation: aapki books vs bank statement.
--
--   * `bank_statement_batches` — ek statement import (account + period).
--   * `bank_statement_lines`   — statement ki har line, uska auto/manual match.
--
-- MATCH KA MODEL (simple aur hamesha sahi):
--   * Matched      : line.matched_transaction_id set hai
--   * Only in bank : line.matched_transaction_id null hai, is_ignored false
--   * Only in books: koi bank_transactions row jisse koi line match nahi hui
--   * Pending      : wahi only-in-books row jiska payment_mode = 'Cheque'
--
-- Isliye results persist karne ki alag table ki zaroorat nahi — match state
-- lines par hi rehti hai, aur unmatched books rows har baar live nikalte hain.
-- Statement dobara paste nahi karni padti (audit trail bhi bacha rehta hai).
--
-- Run ONCE: Supabase Dashboard -> SQL Editor.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- 1) batches
-- ---------------------------------------------------------------------------
create table if not exists public.bank_statement_batches (
  id                        bigint generated by default as identity primary key,
  company_id                bigint not null default 1,
  account_id                bigint not null
                              references public.bank_accounts(id) on delete cascade,
  label                     text,
  period_from               date,
  period_to                 date,
  source                    text not null default 'paste'
                              check (source in ('paste','csv','sbi','bank_export','cash_count')),
  statement_closing_balance numeric(14,2),
  line_count                integer not null default 0,
  created_at                timestamptz not null default now()
);

comment on table public.bank_statement_batches is
  'Ek bank-statement import (account + period). Lines bank_statement_lines me hain.';

create index if not exists bank_statement_batches_company_idx
  on public.bank_statement_batches (company_id, account_id, created_at desc);

-- ---------------------------------------------------------------------------
-- 2) statement lines
-- ---------------------------------------------------------------------------
create table if not exists public.bank_statement_lines (
  id                       bigint generated by default as identity primary key,
  company_id               bigint not null default 1,
  batch_id                 bigint not null
                             references public.bank_statement_batches(id) on delete cascade,
  account_id               bigint not null
                             references public.bank_accounts(id) on delete cascade,
  seq                      integer not null default 0,
  txn_date                 date,
  description              text,
  debit                    numeric(14,2) not null default 0,
  credit                   numeric(14,2) not null default 0,
  balance                  numeric(14,2),
  raw_text                 text,

  -- Match state (yahi persist hota hai)
  -- FK constraint 3) me add hoti hai (bank_transactions.id ka type check karke)
  matched_transaction_id   bigint,
  is_ignored               boolean not null default false,
  note                     text,

  created_at               timestamptz not null default now()
);

comment on column public.bank_statement_lines.matched_transaction_id is
  'Auto-match ke waqt set hota hai; user manually bhi set/undo kar sakta hai.';
comment on column public.bank_statement_lines.is_ignored is
  'True = user ne kaha "ye line ki zaroorat nahi" (jaise bank charges jo books me hain hi nahi).';

create index if not exists bank_statement_lines_batch_idx
  on public.bank_statement_lines (batch_id, seq);
create index if not exists bank_statement_lines_company_idx
  on public.bank_statement_lines (company_id, account_id);
create index if not exists bank_statement_lines_match_idx
  on public.bank_statement_lines (matched_transaction_id)
  where matched_transaction_id is not null;

-- Ek transaction par sirf ek line match ho — warna dobara match hoga.
create unique index if not exists bank_statement_lines_one_match_idx
  on public.bank_statement_lines (company_id, matched_transaction_id)
  where matched_transaction_id is not null;

-- ---------------------------------------------------------------------------
-- 3) FK -> bank_transactions(id)  (type match ho tabhi, warna skip)
-- ---------------------------------------------------------------------------
do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'bank_transactions'
      and column_name = 'id' and data_type = 'bigint'
  ) then
    alter table public.bank_statement_lines
      add constraint bank_statement_lines_txn_fk
      foreign key (matched_transaction_id)
      references public.bank_transactions(id) on delete set null;
    raise notice 'FK added: bank_statement_lines.matched_transaction_id -> bank_transactions(id)';
  else
    raise notice 'SKIP FK: bank_transactions.id type bigint nahi hai (check karein).';
  end if;
end $$;

-- ---------------------------------------------------------------------------
-- 4) RLS — same pattern as bank_accounts
-- ---------------------------------------------------------------------------
alter table public.bank_statement_batches enable row level security;
drop policy if exists "rls_all_bank_statement_batches" on public.bank_statement_batches;
create policy "rls_all_bank_statement_batches" on public.bank_statement_batches
  for all to authenticated using (true) with check (true);

alter table public.bank_statement_lines enable row level security;
drop policy if exists "rls_all_bank_statement_lines" on public.bank_statement_lines;
create policy "rls_all_bank_statement_lines" on public.bank_statement_lines
  for all to authenticated using (true) with check (true);

grant usage on all sequences in schema public to authenticated;

-- ---------------------------------------------------------------------------
-- 5) VERIFY
-- ---------------------------------------------------------------------------
select 'bank_statement_batches' as table_name, count(*) as rows from public.bank_statement_batches
union all
select 'bank_statement_lines', count(*) from public.bank_statement_lines;
