-- Maruti Module Service: Multiple Bank / Cash Accounts + Cash Book
-- Run ONCE in Supabase Dashboard -> SQL Editor.
--
-- Problem: `bank_transactions` ek hi pool hai. Cash, HDFC, SBI, UPI — sab ek
-- me mix. Isliye month-end par pata hi nahi chalta ki cash box me kitna hai aur
-- bank me kitna.
--
-- Fix:
--   1. Naya table `bank_accounts` (Bank / Cash / UPI types ke saath).
--   2. `bank_transactions.account_id` — har transaction kis account se hua.
--   3. `is_transfer` + `transfer_to_account_id` — apne account se dusre account
--      me paisa transfer. Ye income/expense NAHI hai, isliye reports me exclude
--      hota hai (warna cash->bank transfer ek "expense" ban jayega).
--   4. Purane transactions backfill — koi row gaayab nahi hoga.
--
-- Ye script idempotent hai. Dobara chalane par koi duplicate account nahi banta.

-- ---------------------------------------------------------------------------
-- 1) bank_accounts table
-- ---------------------------------------------------------------------------
create table if not exists public.bank_accounts (
  id               bigint generated by default as identity primary key,
  company_id       bigint not null default 1,
  name             text not null,
  account_type     text not null default 'Bank'
                     check (account_type in ('Bank', 'Cash', 'UPI')),
  bank_name        text,
  account_no       text,
  opening_balance  numeric(14,2) not null default 0,
  is_default       boolean not null default false,
  active           boolean not null default true,
  sort_order       integer not null default 0,
  created_at       timestamptz not null default now()
);

comment on table public.bank_accounts is
  'Bank / Cash / UPI accounts. bank_transactions.account_id isse linked hai.';

create index if not exists bank_accounts_company_idx
  on public.bank_accounts (company_id, active);

-- (company_id, name) UNIQUE — ye zaroori hai, warna `on conflict do nothing`
-- kabhi trigger hi nahi hota aur har run par duplicate accounts ban jate hain.
-- Agar pehle se duplicate ban chuke hon to constraint add nahi hoga (unhe
-- `bank-accounts-cleanup.sql` se saaf karein).
do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'bank_accounts_company_name_key'
  ) and not exists (
    select 1 from public.bank_accounts
     group by company_id, name having count(*) > 1
  ) then
    alter table public.bank_accounts
      add constraint bank_accounts_company_name_key unique (company_id, name);
  end if;
end
$$;

-- Ek company me sirf ek default account.
create unique index if not exists bank_accounts_single_default_idx
  on public.bank_accounts (company_id)
  where is_default;

-- ---------------------------------------------------------------------------
-- 2) bank_transactions me naye columns
-- ---------------------------------------------------------------------------
alter table public.bank_transactions
  add column if not exists account_id bigint;

alter table public.bank_transactions
  add column if not exists is_transfer boolean not null default false;

alter table public.bank_transactions
  add column if not exists transfer_to_account_id bigint;

create index if not exists bank_transactions_account_idx
  on public.bank_transactions (company_id, account_id);

create index if not exists bank_transactions_account_date_idx
  on public.bank_transactions (account_id, transaction_date);

-- ---------------------------------------------------------------------------
-- 3) Har company ke liye default accounts banao
--
--    "Bank / General (Old Pool)"  -> saara purana data yahan jaayega.
--                                   opening_balance = 0 rakhna zaroori hai taaki
--                                   per-account running balance purane global
--                                   running balance ke BARABAR rahe (discontinuity nahi).
--    "Cash Box"                    -> naya cash book yahan chalega.
-- ---------------------------------------------------------------------------
do $$
declare
  v_company record;
  v_pool_id bigint;
begin
  for v_company in
    select id from public.companies order by id
  loop
    -- Purana single pool is company ke liye bana do (agar pehle se hai to reuse).
    insert into public.bank_accounts
      (company_id, name, account_type, opening_balance, is_default, active, sort_order)
    values
      (v_company.id, 'Bank / General (Old Pool)', 'Bank', 0, false, true, 0)
    on conflict do nothing;

    select id into v_pool_id
      from public.bank_accounts
     where company_id = v_company.id
       and name = 'Bank / General (Old Pool)';

    -- Cash Box (roz ka cash in/out).
    insert into public.bank_accounts
      (company_id, name, account_type, opening_balance, is_default, active, sort_order)
    values
      (v_company.id, 'Cash Box', 'Cash', 0, false, true, 1)
    on conflict do nothing;

    -- Default account = Old Pool, taaki naye manual entries continuity rakhein.
    update public.bank_accounts
       set is_default = false
     where company_id = v_company.id;

    update public.bank_accounts
       set is_default = true
     where id = v_pool_id;
  end loop;
end
$$;

-- ---------------------------------------------------------------------------
-- 4) Backfill: account_id NULL wale saare purane transactions pool me jaayen
-- ---------------------------------------------------------------------------
update public.bank_transactions bt
   set account_id = a.id
  from public.bank_accounts a
 where a.company_id = bt.company_id
   and a.name = 'Bank / General (Old Pool)'
   and bt.account_id is null;

-- ---------------------------------------------------------------------------
-- 5) RLS — bank_accounts ko bhi wahi treatment jo bank_transactions ko hai
-- ---------------------------------------------------------------------------
alter table public.bank_accounts enable row level security;

drop policy if exists "rls_all_bank_accounts" on public.bank_accounts;
create policy "rls_all_bank_accounts" on public.bank_accounts
  for all to authenticated using (true) with check (true);

grant usage on all sequences in schema public to authenticated;

-- ---------------------------------------------------------------------------
-- 6) VERIFY — iske baad ye chalayein aur output bhejein
-- ---------------------------------------------------------------------------
-- 6a) Accounts dikhne chahiye, aur har transaction ka account_id set hona chahiye:
select a.company_id,
       a.id,
       a.name,
       a.account_type,
       a.opening_balance,
       a.is_default,
       (select count(*) from public.bank_transactions bt
         where bt.account_id = a.id) as txn_count
  from public.bank_accounts a
 order by a.company_id, a.sort_order, a.id;

-- 6b) Yeh COUNT 0 hona chahiye. Agar 0 se zyada hai to koi transaction
--     orphan hai aur wo kisi account view me nahi dikhega:
select count(*) as transactions_without_account
  from public.bank_transactions
 where account_id is null;

-- 6c) Total value cross-check: per-account balance ka total, purane global
--     running balance ke barabar hona chahiye:
select round(sum(coalesce(a.opening_balance, 0)
                 + coalesce(in_.total_in, 0)
                 - coalesce(out_.total_out, 0)), 2) as all_accounts_balance
  from public.bank_accounts a
  left join (
    select account_id, sum(coalesce(payment_in, credit_amount, 0)) as total_in
      from public.bank_transactions group by account_id
  ) in_ on in_.account_id = a.id
  left join (
    select account_id, sum(coalesce(payment_out, debit_amount, 0)) as total_out
      from public.bank_transactions group by account_id
  ) out_ on out_.account_id = a.id;
