-- Maruti Module Service: Item Master migration
-- Run once in Supabase SQL Editor. This script does not drop tables or delete data.

create table if not exists public.item_master (
  id bigint generated by default as identity primary key,
  item_code text,
  item_name text not null,
  category text not null default 'Other',
  unit text not null default 'PCS',
  purchase_price numeric(12,2) not null default 0 check (purchase_price >= 0),
  sale_price numeric(12,2) not null default 0 check (sale_price >= 0),
  opening_stock numeric(14,3) not null default 0 check (opening_stock >= 0),
  minimum_stock numeric(14,3) not null default 0 check (minimum_stock >= 0),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.item_master add column if not exists item_code text;
alter table public.item_master add column if not exists item_name text;
alter table public.item_master add column if not exists category text;
alter table public.item_master add column if not exists unit text;
alter table public.item_master add column if not exists purchase_price numeric(12,2);
alter table public.item_master add column if not exists sale_price numeric(12,2);
alter table public.item_master add column if not exists opening_stock numeric(14,3);
alter table public.item_master add column if not exists minimum_stock numeric(14,3);
alter table public.item_master add column if not exists active boolean;
alter table public.item_master add column if not exists created_at timestamptz;
alter table public.item_master add column if not exists updated_at timestamptz;

alter table public.item_master alter column category set default 'Other';
alter table public.item_master alter column unit set default 'PCS';
alter table public.item_master alter column purchase_price set default 0;
alter table public.item_master alter column sale_price set default 0;
alter table public.item_master alter column opening_stock set default 0;
alter table public.item_master alter column minimum_stock set default 0;
alter table public.item_master alter column active set default true;
alter table public.item_master alter column created_at set default now();
alter table public.item_master alter column updated_at set default now();

create sequence if not exists public.item_master_code_seq start with 1;

-- Continue the automatic ITM sequence after any existing ITM-00001-style codes.
select setval(
  'public.item_master_code_seq',
  coalesce(
    (select max(nullif(regexp_replace(item_code, '\\D', '', 'g'), '')::bigint)
       from public.item_master
      where item_code ~ '^ITM-[0-9]+$'),
    0
  ) + 1,
  false
);

create or replace function public.assign_item_master_code()
returns trigger
language plpgsql
as $$
begin
  if new.item_code is null or btrim(new.item_code) = '' then
    new.item_code := 'ITM-' || lpad(nextval('public.item_master_code_seq')::text, 5, '0');
  end if;
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists trg_assign_item_master_code on public.item_master;
create trigger trg_assign_item_master_code
before insert or update on public.item_master
for each row execute function public.assign_item_master_code();

create unique index if not exists item_master_item_code_unique
  on public.item_master (item_code) where item_code is not null;
create index if not exists item_master_item_name_idx on public.item_master (item_name);
create index if not exists item_master_category_idx on public.item_master (category);
create index if not exists item_master_active_idx on public.item_master (active);

-- Optional, but recommended if RLS is enabled and the existing app uses the anon key.
-- Adapt these policies to your authenticated-user model before using in production.
-- alter table public.item_master enable row level security;
-- create policy "item_master_read" on public.item_master for select to anon using (true);
-- create policy "item_master_write" on public.item_master for all to anon using (true) with check (true);

-- Stock rule for subsequent modules (do not update opening_stock after this migration):
-- available stock = opening_stock + purchase inward quantity - invoiced quantity.
-- Purchase / Invoice integration should use a stock movement ledger or a view built
-- after its final table schema is confirmed. This protects historical opening balances.
